"""Generate johnny5_chassis.xml from the CAD-locked parameters in params.py.

Keeping the MJCF generated (rather than hand-edited) means the simulation
geometry can never silently drift from mechanical/freecad/params.csv. Re-run
whenever the parameter sheet changes:

    python3 simulation/chassis/build_mjcf.py

Modelling choices (see README.md for the full rationale):

* Treads -> four driven wheels (front + rear per side), NOT a deformable belt.
  Deformable track contact is expensive and numerically fragile. A single wheel
  per side collapses the fore-aft contact patch to a point and the tall robot
  nose-dives; front+rear wheels spanning the wheelbase restore the support
  polygon. The real track belt couples the front idler to the rear sprocket, so
  both turn at track speed -- hence all four wheels are driven, in left/right
  pairs (the env writes one command to each side's two wheels).

* DC motor -> torque actuator (gear = stall torque) + joint damping
  b = stall_torque / (2 * no_load_speed). The factor of two splits one physical
  motor's torque-speed line across the two wheels on its side, so the per-side
  behaviour matches a single brushed motor: commanded full torque settles the
  side near its no-load speed instead of accelerating without bound.
"""

from __future__ import annotations

import os

from params import get

_HERE = os.path.dirname(os.path.abspath(__file__))
_OUT = os.path.join(_HERE, "johnny5_chassis.xml")


def _box_diaginertia(mass: float, lx: float, ly: float, lz: float) -> tuple[float, float, float]:
    """Solid-box principal inertias about the box centre."""
    return (
        mass * (ly * ly + lz * lz) / 12.0,
        mass * (lx * lx + lz * lz) / 12.0,
        mass * (lx * lx + ly * ly) / 12.0,
    )


def build_xml() -> str:
    p = get()

    half_w = p.track_width / 2.0          # drive-wheel half-length (cylinder along y)
    com_rel = p.com_height - p.axle_z     # trunk CoM height relative to trunk origin

    # Trunk inertia: solid-box proxy. Footprint length/width from the tub and an
    # EFFECTIVE height taller than the tub to account for the torso/head/arm mass
    # riding above it (the collision geom stays tub-only per the chassis-only brief).
    eff_height = 0.18  # modelling constant; see README "trunk inertia"
    ixx, iyy, izz = _box_diaginertia(p.trunk_mass, p.tub_l, p.tub_w, eff_height)

    # Rear caster effective ground-contact point. The real part is a sprung,
    # swivelling trailing caster; for locomotion it is a rigid low-friction sphere
    # giving the same rearward support. x = half the nominal trail behind the rear
    # track edge (the full trail is the swing radius, not the loaded contact).
    caster_x = -(p.footprint_len / 2.0 + p.caster_trail / 2.0)
    caster_r = p.caster_wheel_radius
    caster_z_rel = caster_r - p.axle_z    # sphere bottom touches ground at rest

    gf = " ".join(f"{v:g}" for v in p.ground_friction)
    wf = " ".join(f"{v:g}" for v in p.wheel_friction)
    gear = p.motor_stall_torque / 2.0                       # split across 2 wheels/side
    damping = p.motor_stall_torque / (2.0 * p.motor_no_load_speed)
    tub_cz = (p.ground_clearance + p.tub_h / 2.0) - p.axle_z
    wb = p.wheelbase / 2.0                 # front/rear wheel x-offset
    yc = p.track_cc / 2.0                  # left/right wheel y-offset

    def wheel(name: str, x: float, y: float) -> str:
        return (
            f'      <body name="{name}" pos="{x:.5f} {y:.5f} 0">\n'
            f'        <joint name="{name}_joint" type="hinge" axis="0 1 0" damping="{damping:.5f}"/>\n'
            f'        <geom name="{name}_geom" type="cylinder" material="wheel_mat" '
            f'fromto="0 {-half_w:.5f} 0 0 {half_w:.5f} 0" size="{p.wheel_radius:.5f}" '
            f'mass="{p.wheel_mass / 2:.4f}" friction="{wf}"/>\n'
            f'      </body>'
        )

    wheels = "\n".join([
        wheel("wheel_rl", -wb, yc),    # rear-left
        wheel("wheel_fl", wb, yc),     # front-left
        wheel("wheel_rr", -wb, -yc),   # rear-right
        wheel("wheel_fr", wb, -yc),    # front-right
    ])

    return f"""<mujoco model="johnny5_chassis">
  <!-- GENERATED by build_mjcf.py from mechanical/freecad/params.csv -- do not edit by hand. -->
  <compiler angle="degree" autolimits="true"/>
  <option timestep="0.002" integrator="implicitfast" gravity="0 0 -9.81"/>

  <default>
    <geom condim="3" friction="{gf}"/>
    <joint damping="0"/>
  </default>

  <asset>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.2 0.25 0.3" rgb2="0.28 0.33 0.4"
             width="512" height="512"/>
    <material name="grid" texture="grid" texrepeat="6 6" reflectance="0.1"/>
    <material name="trunk_mat" rgba="0.85 0.78 0.55 1"/>
    <material name="wheel_mat" rgba="0.12 0.12 0.14 1"/>
    <material name="caster_mat" rgba="0.3 0.3 0.35 1"/>
  </asset>

  <worldbody>
    <light name="top" pos="0 0 1.2" dir="0 0 -1" diffuse="0.8 0.8 0.8"/>
    <geom name="floor" type="plane" size="0 0 0.05" material="grid" friction="{gf}"/>

    <body name="trunk" pos="0 0 {p.axle_z:.5f}">
      <freejoint name="root"/>
      <!-- explicit inertial overrides geom-derived inertia: real mass rides taller than the tub -->
      <inertial pos="0 0 {com_rel:.5f}" mass="{p.trunk_mass:.4f}"
                diaginertia="{ixx:.6f} {iyy:.6f} {izz:.6f}"/>
      <site name="imu" pos="0 0 {com_rel:.5f}" size="0.005" rgba="1 0 0 1"/>

      <!-- chassis tub: collision + visual proxy (chassis-only; no arms/head) -->
      <geom name="tub" type="box" material="trunk_mat"
            pos="0 0 {tub_cz:.5f}"
            size="{p.tub_l / 2:.5f} {p.tub_w / 2:.5f} {p.tub_h / 2:.5f}"/>

      <!-- rear trailing caster, modelled as a rigid low-friction support sphere -->
      <geom name="caster" type="sphere" material="caster_mat"
            pos="{caster_x:.5f} 0 {caster_z_rel:.5f}" size="{caster_r:.5f}"
            friction="0.25 0.005 0.0001"/>

      <!-- four track-contact wheels (front + rear per side), driven in L/R pairs -->
{wheels}
    </body>
  </worldbody>

  <actuator>
    <!-- ctrl in [-1,1] -> torque in [-stall/2, +stall/2] N*m per wheel; per side sums to stall -->
    <motor name="motor_rl" joint="wheel_rl_joint" gear="{gear:.4f}" ctrllimited="true" ctrlrange="-1 1"/>
    <motor name="motor_fl" joint="wheel_fl_joint" gear="{gear:.4f}" ctrllimited="true" ctrlrange="-1 1"/>
    <motor name="motor_rr" joint="wheel_rr_joint" gear="{gear:.4f}" ctrllimited="true" ctrlrange="-1 1"/>
    <motor name="motor_fr" joint="wheel_fr_joint" gear="{gear:.4f}" ctrllimited="true" ctrlrange="-1 1"/>
  </actuator>

  <sensor>
    <gyro name="imu_gyro" site="imu"/>
    <accelerometer name="imu_accel" site="imu"/>
    <framequat name="trunk_quat" objtype="site" objname="imu"/>
    <framepos name="trunk_pos" objtype="site" objname="imu"/>
    <framelinvel name="trunk_linvel" objtype="site" objname="imu"/>
    <jointvel name="enc_rl_vel" joint="wheel_rl_joint"/>
    <jointvel name="enc_rr_vel" joint="wheel_rr_joint"/>
    <jointpos name="enc_rl_pos" joint="wheel_rl_joint"/>
    <jointpos name="enc_rr_pos" joint="wheel_rr_joint"/>
  </sensor>
</mujoco>
"""


def main() -> None:
    xml = build_xml()
    with open(_OUT, "w") as f:
        f.write(xml)
    print(f"wrote {_OUT} ({len(xml)} bytes)")


if __name__ == "__main__":
    main()
